//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Loans = new HashSet<Loan>();
            this.Sanctions = new HashSet<Sanction>();
        }
    
        public int EmployeeID { get; set; }
        public int Antique { get; set; }
        public decimal Salary { get; set; }
        public int IdPerson { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual ICollection<Sanction> Sanctions { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
