//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Students = new HashSet<Student>();
            this.Administrators = new HashSet<Administrator>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int PersonID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int DNI { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string EmailSHA256 { get; set; }
        public int IdRange { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Administrator> Administrators { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Range Range { get; set; }
    }
}
