//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Loans = new HashSet<Loan>();
            this.Sanctions = new HashSet<Sanction>();
        }
    
        public int StudentID { get; set; }
        public int IdPerson { get; set; }
        public bool Sanctioned { get; set; }
        public int IdCareer { get; set; }
        public string IdCondition { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual Condition Condition { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Sanction> Sanctions { get; set; }
    }
}
